### ISSUE TITLE
Numpy failure (Prereq Related)

### ISSUE THREAD

**Issue by tifoji** [bernardcheng/tos_options_dashboard#1]
Ran into this after "python dashboard.py"

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
.....................
Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python"
  * The NumPy version is: "1.19.1"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

This error happens even if the pre-reqs are met

```
pi@raspberrypi:~/tos/tos_options_dashboard $ python -V
Python 3.7.3
pi@raspberrypi:~/tos/tos_options_dashboard $ which python
/usr/bin/python
pi@raspberrypi:~/tos/tos_options_dashboard $ pip list|grep -i numpy
numpy                     1.19.1
```

This is apparently due to [Numpy 14772](https://github.com/numpy/numpy/issues/14772) the root cause is explained within. Anyways the solution works in case anyone else runs into the same issue

`sudo apt-get install libatlas-base-dev`

**Comment by bernardcheng** [comment]
Closing this issue since the solution has been provided. If not, please provide more more information.
